% Text describing the m-files in directory f:\matlab\Comp
% File generated by mkcontnt.m 21-Feb-2011 09:25:59
%   
% Arith06     Arithmetic encoder or decoder 
% Arith07     Arithmetic encoder or decoder 
% entropy     Function returns first order entropy of a source.
% eob3        End Of Block Encoding (or decoding) into (from) three sequences
% Huff06      Huffman encoder/decoder with (or without) recursive splitting
% HuffCode    Based on the codeword lengths this function find the Huffman codewords
% HuffLen     Find the lengths of the Huffman code words
% HuffTabLen  Find how many bits we need to store the Huffman Table information
% HuffTree    Make the Huffman-tree from the lengths of the Huffman codes
% Mat2Vec     Convert an integer matrix to a cell array of vectors,
% TestArith   Test and example of how to use Arith06 and Arith07
% TestHuff    Test and example of how to use Huff06
% uniquant    Uniform scalar quantizer (or inverse quantizer) with threshold
